spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.216.135:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: hyh123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  static-locations: ["/templates/","/resources/","/static","/public/"]  #静态资源处理
  aop:
    auto: true   #开启aop
    proxy-target-class: true
  redis:
    database: 0
    host: 106.54.70.166      #Redis服务器地址
    port: 6379       #Redis服务器连接端口
    password:          #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        # max-wait: -1    #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
        max-idle: 8      #连接池中的最大空闲连接
    timeout: 10000ms   #连接超时时间（毫秒）

server:
  port: 8081



mybatis:
    type-aliases-package: com.lucas.blog.myblog.entity
    mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.lucas.blog.myblog.mapper: DEBUG        #控制台输出sql日志
    root: info
  file: log/blog-dev.log


#配置城市文件路径
city:
  path: /src/main/resources/GeoLite2-City.mmdb



#配置图片上传文件路径

image:
  location: /src/main/resources/static/images/










